"use client";
import Link from "next/link";
import { useState } from "react";
import { useAuth } from "@/hooks/use-auth";
import { useResource } from "@/hooks/use-resource";
import { PageHeader } from "@/components/growth/page-header";
export default function PremiumPage() {
 const { user,plan,loading,signIn,signUp } = useAuth();
 const { data,error,loading: interestLoading,reload } = useResource<{ joined:boolean }>(user ? `/api/premium-interest?account=${user.id}` : null);
 const [busy,setBusy] = useState(false), [message,setMessage] = useState("");
 async function change() { if (!user) { await signUp(); return; } setBusy(true); try { const r = await fetch("/api/premium-interest",{method:data?.joined ? "DELETE" : "POST"}); const b = await r.json(); if (!r.ok) throw new Error(b.error); setMessage(b.joined ? "You’re on the early access list. Nothing has been charged." : "You’ve left the early access list."); reload(); } catch(e) { setMessage(e instanceof Error ? e.message : "Could not update early access."); } finally { setBusy(false); } }
 return <div className="growth-page"><PageHeader/><main className="growth-main"><div className="growth-title"><div><span className="eyebrow">PredictArena Premium · Early access</span><h1>A closer look at the numbers.</h1><p>Detailed model explanations alongside a public record you can check for yourself.</p></div></div><div className="plan-grid"><section className="plan-card"><span className="eyebrow">Free</span><h2>Follow the matches</h2><strong className="plan-price">₦0</strong><ul><li>Upcoming match probabilities</li><li>Public forecast record and results</li><li>Account-saved forecasts and preferences</li><li>Calendar reminders and device-saved slips</li></ul><Link className="growth-link" href="/">Browse predictions</Link></section><section className="plan-card premium-plan"><span className="eyebrow">Premium · Planned launch price</span><h2>Understand the forecast</h2><strong className="plan-price">₦3,000 <small>/ month</small></strong><ul><li>Detailed model factor explanations</li><li>The evidence behind each forecast</li><li>Match-level limitations and sample context</li></ul>{loading ? <p role="status">Checking account…</p> : plan === "premium" ? <p className="result-tag correct">Premium access active</p> : <button className="growth-primary" disabled={busy || interestLoading} onClick={() => void change()}>{busy ? "Updating…" : data?.joined ? "Leave early access list" : "Join early access"}</button>}<p className="growth-note">Paid subscriptions are not open yet. Joining records your interest; it does not charge you or activate Premium. The launch price may change.</p></section></div>{(message || error) && <p className="growth-notice" role="status">{message || error}</p>}{!user && <p className="growth-note">Already have an account? <button className="text-button" onClick={() => void signIn()}>Sign in</button></p>}<p className="growth-note">Premium provides more analysis. Results remain uncertain, and the public record stays free.</p></main></div>;
}
