"use client";
import Link from "next/link";
import { useState } from "react";
import { PageHeader } from "@/components/growth/page-header";
import { useResource } from "@/hooks/use-resource";
import { resultOutcome, type ArchivedForecast, type Performance } from "@/lib/archive";
const leagues = [["39","Premier League"],["2","Champions League"],["140","La Liga"],["135","Serie A"],["78","Bundesliga"],["61","Ligue 1"]];
const wat = (date: string) => new Date(date).toLocaleString("en-NG", { timeZone: "Africa/Lagos", dateStyle: "medium", timeStyle: "short" });
export default function PerformancePage() {
 const [league,setLeague] = useState(""), [page,setPage] = useState(0);
 const { data,error,loading,reload } = useResource<{ forecasts: ArchivedForecast[]; total: number; performance: Performance }>(`/api/performance?league=${league}&page=${page}`);
 const m = data?.performance;
 return <div className="growth-page"><PageHeader/><main className="growth-main">
  <div className="growth-title"><div><span className="eyebrow">Football · Home / Draw / Away</span><h1>Forecast record</h1><p>The first eligible forecast saved before kickoff, alongside the final result.</p></div><label>Competition<select value={league} onChange={e => { setLeague(e.target.value); setPage(0); }}><option value="">All competitions</option>{leagues.map(([id,name]) => <option key={id} value={id}>{name}</option>)}</select></label></div>
  {error ? <div className="growth-empty" role="alert"><p>{error}</p><button onClick={reload}>Try again</button></div> : loading ? <div className="growth-loading" role="status">Loading the prediction record…</div> : <>
   <div className="record-stats"><div><span>Published forecasts</span><strong>{m?.published ?? 0}</strong></div><div><span>Final results</span><strong>{m?.settled ?? 0}</strong></div><div><span>Strongest outcome correct</span><strong>{m?.winRate == null ? "—" : `${(m.winRate*100).toFixed(1)}%`}</strong><small>{m?.correct ?? 0} / {m?.settled ?? 0} settled</small></div><div><span>Brier score · lower is better</span><strong>{m?.brier == null ? "—" : m.brier.toFixed(3)}</strong><small>Three-outcome score · 0 to 2</small></div><div><span>Log loss · lower is better</span><strong>{m?.logLoss == null ? "—" : m.logLoss.toFixed(3)}</strong></div></div>
   <p className="growth-note">{m?.since ? `Recording since ${wat(m.since)} WAT.` : "Recording starts with the first eligible forecast; past forecasts have not been reconstructed."} Includes provider-confirmed fixtures with at least 10 historical matches and valid probabilities. Manual entries and forecasts without sufficient history are excluded. Final results use 90 minutes, including stoppage time.</p>
   {!data?.forecasts.length ? <div className="growth-empty"><h2>The record starts here</h2><p>Eligible upcoming forecasts appear after a successful refresh. Results remain blank until final scores arrive.</p><Link href="/">Browse upcoming matches</Link></div> : <>
    <div className="record-table-wrap"><table className="record-table"><caption className="sr-only">First published match forecasts and final results. Timestamps are in West Africa Time.</caption><thead><tr><th>Match / kickoff WAT</th><th>Home / Draw / Away</th><th>Strongest outcome</th><th>Final result</th><th>Recorded before kickoff</th></tr></thead><tbody>{data.forecasts.map(a => {
     const r = a.fixture_results, correct = r ? resultOutcome(r.home_score,r.away_score) === a.strongest_outcome : null;
     return <tr key={a.fixture_id}><td><strong>{a.home} vs {a.away}</strong><small>{a.league} · {wat(a.kickoff_at)}</small></td><td>{a.probabilities.map(p => `${p}%`).join(" / ")}</td><td>{a.strongest_outcome === "home" ? a.home : a.strongest_outcome === "away" ? a.away : "Draw"}</td><td>{r ? <><strong>{r.home_score}–{r.away_score}</strong><span className={`result-tag ${correct ? "correct" : "missed"}`}>{correct ? "Correct" : "Missed"}</span></> : <span className="result-tag pending">Awaiting final result</span>}</td><td><small>{wat(a.published_at)} WAT</small><small>{a.model_version}</small></td></tr>;
    })}</tbody></table></div><div className="record-pagination"><button disabled={!page} onClick={() => setPage(x => x-1)}>Previous</button><span>Page {page+1} of {Math.max(1,Math.ceil(data.total/30))} · {data.total} forecasts</span><button disabled={(page+1)*30 >= data.total} onClick={() => setPage(x => x+1)}>Next</button></div>
   </>}
   <section className="record-method"><h2>Do the percentages hold up?</h2><p>Compare the predicted chance of the strongest outcome with how often it happened. Each group needs a substantial sample before drawing conclusions.</p>{m?.calibration.length ? <div className="record-table-wrap"><table className="record-table"><thead><tr><th>Probability range</th><th>Matches</th><th>Average predicted</th><th>Actually correct</th></tr></thead><tbody>{m.calibration.map(b => <tr key={b.bucket}><td>{b.bucket*10}–{b.bucket*10+10}%</td><td>{b.count}</td><td>{(b.expected*100).toFixed(1)}%</td><td>{(b.actual*100).toFixed(1)}%</td></tr>)}</tbody></table></div> : <p className="growth-note">Calibration appears after the first forecasts have final results.</p>}</section>
  </>}
  <section className="record-method"><h2>What this record measures</h2><p>One first-published home/draw/away forecast per fixture. The headline percentage measures the strongest 1X2 outcome, including draws. It does not measure slip success, every market, or betting profit. Brier score sums the squared probability errors across all three outcomes. Log loss uses the probability assigned to the actual outcome, with a floor of 0.000001.</p><p>The historical bookmaker benchmark on the home page is a separate test. The publication metrics here are not backtest results.</p></section>
 </main></div>;
}
